# Generated by Django 5.2.8 on 2025-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experimento_usuario_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='estado',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
