# Generated by Django 5.2.8 on 2025-11-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pontoscoleta_delete_experimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cpf_cnpj',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Doador', 'Doador'), ('Empresa', 'Empresa')], default='Doador', max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CriarDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doacao', models.CharField(max_length=100)),
                ('especificacao', models.TextField()),
                ('endereco', models.CharField(max_length=200)),
                ('descricao_geral', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('condicao', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Para peças', 'Para peças')], default='Usado', max_length=100)),
                ('fotos_eletronico', models.ImageField(blank=True, null=True, upload_to='fotos_eletronicos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
