# Generated by Django 5.2.8 on 2025-12-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_cpf_cnpj_userprofile_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Doador', 'Doador'), ('Empresa', 'Empresa')], max_length=8),
        ),
    ]
