# Generated by Django 5.2.8 on 2025-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('DOADOR', 'Doador'), ('EMPRESA', 'Empresa')], max_length=8),
        ),
    ]
