# Generated by Django 5.2.8 on 2025-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoscoleta',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='criardoacao',
            name='condicao',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('PARA PEÇAS', 'Para peças')], default='Usado', max_length=100),
        ),
    ]
