# Generated by Django 5.2.8 on 2025-12-12 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pontoscoleta_numero_alter_criardoacao_condicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CriarDoacao',
            new_name='Doacao',
        ),
    ]
