# Generated by Django 5.2.8 on 2025-12-17 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_criardoacao_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
