# Generated by Django 5.2.8 on 2025-12-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='criado_em',
        ),
    ]
